project_id = "bpurlsnfjnzriyrnuknq"

[functions.search-products]
verify_jwt = false

[functions.validate-order]
verify_jwt = false

[functions.reset-password]
verify_jwt = false

[functions.visual-search]
verify_jwt = false