// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qefpoipccckqaptmmpop.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFlZnBvaXBjY2NrcWFwdG1tcG9wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMTExOTAsImV4cCI6MjA3Mzc4NzE5MH0.6S0Efku-YZJoYYKk4AZRVuQ1WQpaLntjAPH8iuAiKAg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});